In [0]:
import numpy as np

In [7]:
array1 = np.array([[3,2,0.5,7,0],[1,12,3,4,5]], dtype='int32')  # making a array in 2D
print(array1)



[[ 3  2  0  7  0]
 [ 1 12  3  4  5]]


In [8]:
array1.shape  # for finding shape


(2, 5)

In [9]:
array1.dtype # for finding data type

dtype('int32')

In [10]:
np.zeros(4) # making a array containing all zeroes

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,6))  # making a matices in which all element are zeroes


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(6).dtype # it takes float64 beacuse no lose of data


dtype('float64')

In [13]:
np.empty((4,6)) # it allocate memory omly

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
array1*array1 # for multiplication 

array([[  9,   4,   0,  49,   0],
       [  1, 144,   9,  16,  25]], dtype=int32)

In [15]:
array1*array1 # for multiplication 

array([[  9,   4,   0,  49,   0],
       [  1, 144,   9,  16,  25]], dtype=int32)

In [16]:
array1+array1 # for addition

array([[ 6,  4,  0, 14,  0],
       [ 2, 24,  6,  8, 10]], dtype=int32)

In [17]:
1/array1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.33333333, 0.5       ,        inf, 0.14285714,        inf],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

In [0]:
#@title Slicing 

                                                                       
array2 = np.array([5,4,64,3,3,3])
arr = array2[4:6]


In [19]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a.sum(axis=0) # for column

array([5, 7, 9])

In [21]:
a.sum(axis=1) # for row

array([ 6, 15])

In [22]:
b = np.array([[7,8,9],[2,8,0]])
b


array([[7, 8, 9],
       [2, 8, 0]])

In [23]:
np.dot(a,b.transpose()) # for transpose

array([[ 50,  18],
       [122,  48]])

In [24]:
np.cross(a,b) # for cross product

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [25]:
b
np.sort(b) # for rows


array([[7, 8, 9],
       [0, 2, 8]])

In [26]:
%%time
np.sort(b,axis=0,kind='qicksort') # for columns

CPU times: user 442 µs, sys: 90 µs, total: 532 µs
Wall time: 796 µs


array([[2, 8, 0],
       [7, 8, 9]])

In [27]:
a = np.arange(8) # for arranging element
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
b = np.array([12,3,4,1,5,6,3,3,335,66,7,8,32,1,66,90,12,13,55,21,43,36,2,1]) # for reshape
#b = b.reshape(6,4)


In [29]:

b


array([ 12,   3,   4,   1,   5,   6,   3,   3, 335,  66,   7,   8,  32,
         1,  66,  90,  12,  13,  55,  21,  43,  36,   2,   1])

In [30]:
np.argsort(b)


array([23,  3, 13, 22,  1,  6,  7,  2,  4,  5, 10, 11, 16,  0, 17, 19, 12,
       21, 20, 18, 14,  9, 15,  8])

In [31]:
np.argmin(b)

3

In [32]:
np.argmax(b)

8